name: TeamCity Tests

on: push

jobs:
  run_teamcity_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Install ifconfig
        run: sudo apt-get update && sudo apt-get install -y net-tools

      - name: Set up host environment variables
        run: |
          echo "HOST=$(ifconfig | grep -E '([0-9]{1,3}\.){3}[0-9]{1,3}' | grep -v 127.0.0.1 | awk '{ print $2 }' | head -n 1)" >> $GITHUB_ENV

      - name: Setup host config.properties
        run: |
          echo "host=${{ env.HOST }}:8111" > src/main/resources/config.properties
          echo "remote=http://${{ env.HOST }}:4444/wd/hub" >> src/main/resources/config.properties
          echo "browser=chrome" >> src/main/resources/config.properties

      - name: Create Selenoid Config Directory
        run: mkdir -p config

      - name: Copy Browsers Config
        run: cp config/browsers.json config/

      - name: Print config.properties
        run: cat src/main/resources/config.properties

      - name: Pull Selenoid Chrome/Firefox/Opera
        run: docker pull selenoid/vnc:chrome_91.0

      - name: Run Selenoid
        run: |
          docker run -d --name selenoid \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v $(pwd)/config/:/etc/selenoid/:ro \
          -p 4444:4444 \
          aerokube/selenoid:latest-release

      - name: Run TeamCity server
        run: |
          docker run -u 0 -d --name teamcity-server \
          -v $(pwd)/tmp/teamcity_server/datadir:/data/teamcity_server/datadir \
          -v $(pwd)/tmp/teamcity_server/logs:/opt/teamcity/logs \
          -p 8111:8111 \
          jetbrains/teamcity-server:2023.11.1

      - name: Run TeamCity agent
        run: |
          docker run -e SERVER_URL=http://${{ env.HOST }}:8111 -u 0 -d --name teamcity-agent \
          -v $(pwd)/tmp/teamcity_agent/conf:/data/teamcity_agent/conf \
          jetbrains/teamcity-agent:2023.11.1

      - name: Wait for TeamCity server to be ready
        run: sleep 30

      - name: Run TeamCity setup test
        run: mvn clean test -Dtest=TeamCitySetupTest#startUpTest
        working-directory: ${{ github.workspace }}

      - name: List running Docker containers
        run: docker ps

      - name: Print TeamCity server logs directory
        run: ls -l $(pwd)/tmp/teamcity_server/logs

      - name: Print TeamCity server log file for verification
        run: cat $(pwd)/tmp/teamcity_server/logs/teamcity-server.log

      - name: Set up superUserToken environment variable
        run: |
          logs_dir=$(pwd)/tmp/teamcity_server/logs
          max_retries=20
          count=0
          while [ $count -lt $max_retries ]; do
            if grep -q 'Super user authentication token' "$logs_dir/teamcity-server.log"; then
              echo "SUPER_USER_TOKEN=$(grep 'Super user authentication token' $logs_dir/teamcity-server.log | tail -n 1 | awk '{print $8}')" >> $GITHUB_ENV
              break
            fi
            echo "Waiting for super user token in logs..."
            sleep 10
            ((count++))
          done
          if [ $count -ge $max_retries ]; then
            echo "Super user token not found in logs" >&2
            exit 1
          fi

      - name: Print relevant part of TeamCity server log file
        run: grep 'Super user authentication token' $(pwd)/tmp/teamcity_server/logs/teamcity-server.log

      - name: Set up superUserToken config property
        run: echo "superUserToken=${{ env.SUPER_USER_TOKEN }}" >> src/main/resources/config.properties

      - name: Verify config.properties after setting superUserToken
        run: cat src/main/resources/config.properties
